[package]
name = "sdk_docs_snippets"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bip39 = { version = "2", features = ["rand"] }
breez-sdk-core = { git = "https://github.com/breez/breez-sdk", rev = "a9d208a0b8aa074cd6ab0bc490ecd074c704197a" }
log = "0.4"
tokio = "1.29"
