[book]
authors = ["Roei Erez"]
language = "en"
multilingual = true
src = "src"
title = "Breez SDK - Greenlight"

[output.html]
theme="theme"
additional-css = ["task-lists.css"]
additional-js = ["tabs.js"]
git-repository-url = "https://github.com/breez/breez-sdk-docs"
edit-url-template = "https://github.com/breez/breez-sdk-docs/edit/main/{path}"
no-section-label = true

[output.html.fold]
enable = true

[output.html.print]
enable = false

[preprocessor.snippets]
after = ["links"]
