[book]
authors = ["Roei Erez"]
language = "en"
multilingual = true
src = "src"
title = "Breez SDK"

[output.html]
additional-js = ["tabs.js", "highlight.js"]
git-repository-url = "https://github.com/breez/breez-sdk-docs"
edit-url-template = "https://github.com/breez/breez-sdk-docs/edit/main/{path}"

[output.html.print]
enable = false