[book]
authors = ["Roei Erez"]
language = "en"
multilingual = true
src = "src"
title = "Breez SDK - Greenlight"

[output.html]
theme="theme"
additional-js = ["tabs.js"]
git-repository-url = "https://github.com/breez/breez-sdk-docs"
edit-url-template = "https://github.com/breez/breez-sdk-docs/edit/main/{path}"

[output.html.print]
enable = false

[preprocessor.snippets]
after = ["links"]
