name: dart_snippets
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  breez_sdk:
    path: ./packages/breez-sdk-flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
